from __future__ import annotations

from enum import Enum


class RobotState(str, Enum):
    SEARCHING = "SEARCHING"
    WASTE_DETECTED = "WASTE_DETECTED"
    NAVIGATING = "NAVIGATING"
    POSITIONING = "POSITIONING"
    ARM_APPROACHING = "ARM_APPROACHING"
    GRASPING = "GRASPING"
    LIFTING = "LIFTING"
    MOVING_TO_BASKET = "MOVING_TO_BASKET"
    RELEASING = "RELEASING"
    RETURNING_ARM = "RETURNING_ARM"
    STOPPED = "STOPPED"
    COMPLETE = "COMPLETE"
