from __future__ import annotations

from enum import Enum


class RobotState(str, Enum):
    IDLE = "IDLE"
    PATROLLING = "PATROLLING"
    POTENTIAL_GARBAGE_FOUND = "POTENTIAL_GARBAGE_FOUND"
    CAPTURING_IMAGE = "CAPTURING_IMAGE"
    GEMINI_ANALYSIS = "GEMINI_ANALYSIS"
    APPROACHING_TARGET = "APPROACHING_TARGET"
    ARM_POSITIONING = "ARM_POSITIONING"
    GRABBING = "GRABBING"
    LIFTING = "LIFTING"
    MOVING_TO_BIN = "MOVING_TO_BIN"
    RELEASING = "RELEASING"
    ARM_RESET = "ARM_RESET"
    STOPPED = "STOPPED"
    COMPLETE = "COMPLETE"
